name: parkingpage

services:
  parkingpage:
    image: ghcr.io/ivancarlosti/parkingpage:latest
    env_file: .env
    container_name: parkingpage
    restart: unless-stopped
    volumes:
      - ./sites:/config/sites # mount a folder with multiple .env files for multi-site support
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php.rule=Host(`subdomain.example.com`)"   ### CHANGE subdomain.example.com TO YOUR DOMAIN ###
      - "traefik.http.routers.php.entrypoints=websecure"
      - "traefik.http.routers.php.tls.certresolver=letsencrypt"
    networks:
      - web

  traefik:
    image: traefik:latest
    container_name: parkingpage-traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --certificatesresolvers.letsencrypt.acme.email=email@example.com   ### CHANGE email@example.com TO YOUR EMAIL ADDRESS ###
      - --certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: false
